// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJllO6in8PoYDYSjFR6XyeUlw8C4JBlzs',
    appId: '1:580225476958:web:a69ba399e8af8d740207cf',
    messagingSenderId: '580225476958',
    projectId: 'notes-edc16',
    authDomain: 'notes-edc16.firebaseapp.com',
    storageBucket: 'notes-edc16.appspot.com',
    measurementId: 'G-W146GCF6PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQUmXW1BeE4eNpaIOtuV-c8tHcs1AmyHo',
    appId: '1:580225476958:android:420f172f1e2daf050207cf',
    messagingSenderId: '580225476958',
    projectId: 'notes-edc16',
    storageBucket: 'notes-edc16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK_E8iJTZ1LgiNZEP-_puhlmnO_DhaNnA',
    appId: '1:580225476958:ios:47f7ecd0394ac5920207cf',
    messagingSenderId: '580225476958',
    projectId: 'notes-edc16',
    storageBucket: 'notes-edc16.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK_E8iJTZ1LgiNZEP-_puhlmnO_DhaNnA',
    appId: '1:580225476958:ios:47f7ecd0394ac5920207cf',
    messagingSenderId: '580225476958',
    projectId: 'notes-edc16',
    storageBucket: 'notes-edc16.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJllO6in8PoYDYSjFR6XyeUlw8C4JBlzs',
    appId: '1:580225476958:web:2a39e1d96ece6cdb0207cf',
    messagingSenderId: '580225476958',
    projectId: 'notes-edc16',
    authDomain: 'notes-edc16.firebaseapp.com',
    storageBucket: 'notes-edc16.appspot.com',
    measurementId: 'G-59DN38R5RV',
  );
}
